taxi_riders:

  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: datacamp-378414
      dataset: dbt_dev_datacamp
      threads: 4
      job_retries: 2
      location: asia-east2
      keyfile_json:
        type: ${{SECRET.TYPE_BEGQUERY}},
        project_id: ${{SECRET.PROJECT_ID_BQ}},
        private_key_id: ${{SECRET.PRIVATE_KEY_ID_BQ}},
        private_key: ${{SECRET.PRIVATE_KEY_BQ}},
        client_email: ${{SECRET.CLIENT_EMAIL_BQ}},
        client_id: ${{SECRET.CLIENT_ID_BQ}},
        auth_uri: ${{SECRET.AUTH_URI}},
        token_uri: ${{SECRET.TOKER_URI_BQ}},
        auth_provider_x509_cert_url: ${{SECRET.AUTH_PROVIDER_BQ}},
        client_x509_cert_url: ${{SECRET.CLIENT_X509_BQ}}

    pr:
      type: bigquery
      method: service-account
      project: datacamp-378414
      dataset: dbt_pr_datacamp
      threads: 4
      job_retries: 2
      location: asia-east2
      keyfile_json:
        type: ${{SECRET.TYPE_BEGQUERY}},
        project_id: ${{SECRET.PROJECT_ID_BQ}},
        private_key_id: ${{SECRET.PRIVATE_KEY_ID_BQ}},
        private_key: ${{SECRET.PRIVATE_KEY_BQ}},
        client_email: ${{SECRET.CLIENT_EMAIL_BQ}},
        client_id: ${{SECRET.CLIENT_ID_BQ}},
        auth_uri: ${{SECRET.AUTH_URI}},
        token_uri: ${{SECRET.TOKER_URI_BQ}},
        auth_provider_x509_cert_url: ${{SECRET.AUTH_PROVIDER_BQ}},
        client_x509_cert_url: ${{SECRET.CLIENT_X509_BQ}}
    prod:
      type: bigquery
      method: service-account
      project: datacamp-378414
      dataset: dbt_prod_datacamp
      threads: 4
      job_retries: 2
      location: asia-east2
      keyfile_json:
        type: ${{SECRET.TYPE_BEGQUERY}},
        project_id: ${{SECRET.PROJECT_ID_BQ}},
        private_key_id: ${{SECRET.PRIVATE_KEY_ID_BQ}},
        private_key: ${{SECRET.PRIVATE_KEY_BQ}},
        client_email: ${{SECRET.CLIENT_EMAIL_BQ}},
        client_id: ${{SECRET.CLIENT_ID_BQ}},
        auth_uri: ${{SECRET.AUTH_URI}},
        token_uri: ${{SECRET.TOKER_URI_BQ}},
        auth_provider_x509_cert_url: ${{SECRET.AUTH_PROVIDER_BQ}},
        client_x509_cert_url: ${{SECRET.CLIENT_X509_BQ}}

      
