services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "C:\\Users\\Дмитрий\\WorkFolder\\Программирование\\GitHub\\dataeng-zoomcamp\\week_1_basics_n_setup\\ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"


  