name: My Workflow

on:
    push:
      branches: [dbt_datacamp_dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Build
      run: |
        echo "Secret Value: ${{secrets.PRIVATE_KEY_ID_BQ}}"
